### ISSUE TITLE
Reproducibility of Results

### ISSUE THREAD

**Issue by RuihangWang** [AgrawalAmey/safe-explorer#2]
Hi Amey,

I tried to run your code to reproduce the results of the original paper. However, the performance is not so good. The original paper claims they can achieve zero violations. However, my implementation based on your code violates frequently during exploration. 

Wondering if you can achieve better performance as described in the paper. Looking forward to your reply.

Thanks

**Comment by AgrawalAmey** [comment]
Hi @RuihangWang ,

It is an old project, I don't remember the specifics but as far as I can tell there are some key details implementation details in the original paper. If you are able to figure out the missing details any contributions are welcome. Thanks!
